### ISSUE TITLE
Epic 1.1 Access Control V2 - Implement Google Auth, captcha, cookies and error handling.

### ISSUE THREAD

**Issue by Ahmedr275** [radicalxdev/marvel-platform#193]
### **GitHub Issue: Core Marvel - Access Control Implementation**

---

**Overview**  
This issue focuses on implementing critical access control features for the Marvel platform to enhance user authentication security, improve usability, and ensure compliance with privacy regulations. The scope includes enabling Google authentication, integrating captcha verification, configuring cookie session settings, and implementing robust error handling.

---

#### **1. Enable Google Authentication**
- **Firebase Configuration**:  
  - Enable Google Authentication in the Firebase Console.  
  - Update the Firebase configuration file (e.g., `firebaseConfig.js`) to include the Google Auth provider.  
- **Frontend Components**:  
  - Add Google Sign-In and Sign-Up buttons to `SignInForm.jsx` and `SignUpForm.jsx`.  
  - Style the buttons to match the application's theme.  
- **Google Auth Logic**:  
  - Implement Google sign-in and sign-up logic using Firebase Auth's Google provider.  
  - Handle success and error scenarios appropriately.  
- **Update Authentication State**:  
  - Update the Redux store or context to reflect the user's authentication state.  
  - Ensure the UI updates correctly based on the authentication state.  
- **Testing**:  
  - Thoroughly test the Google Sign-In and Sign-Up functionality on different devices and browsers.  
  - Ensure all edge cases are handled effectively.

#### **2. Add Captcha for Login Attempts**
- Integrate a captcha solution (e.g., reCAPTCHA or hCaptcha) into the sign-in and sign-up forms.  
- Prevent automated attacks while maintaining user-friendly interactions.  
- Validate and test the captcha functionality to ensure reliability and usability.

#### **3. Configure Cookie Session Compliance**
- Configure session cookies to comply with GDPR and similar privacy standards.  
- Implement secure, http-only cookies with proper expiration and user consent mechanisms.  
- Test cookie configurations for compliance and functionality across browsers.

#### **4. Implement Error Handling**
- Develop user-friendly error messages for authentication scenarios:  
  - Invalid credentials.  
  - Expired sessions.  
  - Failed Google sign-ins.  
- Log errors for backend monitoring and debugging purposes.  
- Ensure error messages are clear and actionable for users.

---

### **Acceptance Criteria**

- [ ] Google Authentication is enabled and working for both sign-in and sign-up.  
- [ ] Users can log in and sign up using their Google accounts seamlessly.  
- [ ] Captcha verification is integrated and functional on all login and sign-up attempts.  
- [ ] Session cookies comply with GDPR and other privacy standards.  
- [ ] User-friendly error messages are displayed for all authentication issues.  
- [ ] Errors are logged appropriately for monitoring and debugging.  
- [ ] Thorough testing is completed, and all edge cases are handled effectively.  

---

### **Resources**

1. [Firebase Documentation - Authentication](https://firebase.google.com/docs/auth)  
2. [reCAPTCHA API Documentation](https://developers.google.com/recaptcha)  
3. [Cookie Management Guidelines](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)  
4. [Designs](https://www.figma.com/proto/lUJEUgY7DYLCJcx8db3CBK/Marvel---Live?node-id=260-1567&node-type=canvas&t=IFSJpFvD7SMAmycQ-1&scaling=min-zoom&content-scaling=fixed&page-id=260%3A1289)

---

**Notes**  
This issue combines multiple access control features into a unified implementation plan. Developers should ensure each feature is tested thoroughly for functionality, security, and compliance.

**Comment by liamohkay** [comment]
Hey can I be assigned to this ticket? I've set up firebase auth & google oauth in side projects before.

**Comment by Ahmedr275** [comment]
Hey @liamohkay, you can definitely pick up the issue and work on it. Our process for issue assignment is focused on first to PR so multiple contributors can work on an issue and can bring in their own improvements/ideas to the issue as well. Read more [here](https://lab.realityai.tech/posts/74703654)

**Comment by liamohkay** [comment]
Thanks @Ahmedr275 ! I picked it up and have everything sorted besides the cookies & testing. Hopefully will have a good looking PR for you guys in a couple days.

**Comment by liamohkay** [comment]
@Ahmedr275 

In regards to section 3. Configure Cookie Session Compliance.

Firebase already handles client side cookies for persistent auth sessions. Do you also want me to handle the server side / middleware portion as well? Or is it something that can be pushed until the Next 13 upgrade (as some of the 12 implementation might get deprecated??)

**Comment by Ahmedr275** [comment]
Hey @liamohkay, that can be pushed to next upgrade.

**Comment by liamohkay** [comment]
> Hey @liamohkay, that can be pushed to next upgrade.

@Ahmedr275 I built out all the encryption and session helpers so happy to take that ticket once the next version changes. Ill have a PR in for the of this one in by EOD Saturday.

**Comment by Code2voyager** [comment]
How should I start contributing to this issue of project?

**Comment by liamohkay** [comment]
> How should I start contributing to this issue of project?

Just start working on it and submit a PR. I'm about to send one in so they'll likely pick the good parts from both of ours and combine it into 1.

**Comment by fkariche7913** [comment]
Hi, can I start working in this issue

**Comment by LarissaBrown** [comment]
I am receiving this error regarding signing into the firebase project:  
extensions: Unable to look up project number for kai-platform-sandbox.
[0]  If this is a real project, ensure that you are logged in and have access to it.
How do I get access to the marvel-ai kai-platform-sandbox?

**Comment by Know167** [comment]
@Ahmedr275 I found another issue while setting up local development environment, the given user-id: 'user@test.com' and password: 'Test@123' in the [[README.md](https://github.com/Know167/marvel-platform/blob/develop/README.md#accessing-the-application)] for development purposes doesn't work on the login page and gives an authentication error.

**Comment by liamohkay** [comment]
@LarissaBrown @Know167 are these issues for one of the active PR branches or just general issues on the develop branch?

**Comment by liamohkay** [comment]
> @Ahmedr275 I found another issue while setting up local development environment, the given user-id: '[user@test.com](mailto:user@test.com)' and password: 'Test@123' in the [[README.md](https://github.com/Know167/marvel-platform/blob/develop/README.md#accessing-the-application)] for development purposes doesn't work on the login page and gives an authentication error.

Try enabling email & password signup on firebase console 
<img width="1142" alt="Screen Shot 2024-12-30 at 11 08 09 AM" src="https://github.com/user-attachments/assets/3c5ebd23-08fa-47ce-9319-f9a3ce40af73" />

**Comment by LarissaBrown** [comment]
@liamohkay this is not for any active PR branch. I am setting up my local environment on a branch I created for this feature story.

**Comment by LarissaBrown** [comment]
In regards to the error posted above: extensions: Unable to look up project number for kai-platform-sandbox.
[0]  If this is a real project, ensure that you are logged in and have access to it. 

This is what I am using in the firebaseConfig.js  inside the .env file <img width="787" alt="Image" src="https://github.com/user-attachments/assets/4aa49db4-5bc1-404c-b636-1d16ca841a32" />

**Comment by LarissaBrown** [comment]
@Ahmedr275 regarding the last 2 comments from me, I need login information for the dashboard for the above credentials. How do I get these? I have my login for Firebase but that does not help me login to use the firebaseConfig credentials above.

**Comment by Cosmodocus** [comment]
> @ Ahmedr275 regarding the last 2 comments from me, I need login information for the dashboard for the above credentials. How do I get these? I have my login for Firebase but that does not help me login to use the firebaseConfig credentials above.

Hi @LarissaBrown, I'd be happy to help!
So it sounds like you're using your own Firebase project setup to utilize your own credentials. 

The issue if you're doing so is that the current env you're using is our prod config instead of yours. You're using setup #2 in our ReadMe file which is recommended, as it doesn't require your own setup.  

Take a look at our ReadMe file in setup for more info.

I hope this helped! If not, please include a loom video and a detailed description of the problem.

**Comment by LarissaBrown** [comment]
> > @ Ahmedr275 regarding the last 2 comments from me, I need login information for the dashboard for the above credentials. How do I get these? I have my login for Firebase but that does not help me login to use the firebaseConfig credentials above.
> 
> Hi [@LarissaBrown](https://github.com/LarissaBrown), I'd be happy to help! So it sounds like you're using your own Firebase project setup to utilize your own credentials.
> 
> The issue if you're doing so is that the current env you're using is our prod config instead of yours. You're using setup [#2](https://github.com/marvelai-org/marvel-platform/pull/2) in our ReadMe file which is recommended, as it doesn't require your own setup.
> 
> Take a look at our ReadMe file in setup for more info.
> 
> I hope this helped! If not, please include a loom video and a detailed description of the problem.

AH, @Ahmedr275 I see what I did. I had the correct credentials for the .env file but did not login with the given Firebase login email and password. Thank you for taking the time to point me back to the READ ME file.

**Comment by LarissaBrown** [comment]
How do I access the Firebase Console for Marvel AI (not my account) to enable Google Authentication in the Firebase Console? I can use the test sign-in and password for access with the Development Server running but I do not have the signing-in username and password for the Firebase console. Using my own clearly would not then have access to the Marvel AI Database.

**Comment by liamohkay** [comment]
> How do I access the Firebase Console for Marvel AI (not my account) to enable Google Authentication in the Firebase Console? I can use the test sign-in and password for access with the Development Server running but I do not have the signing-in username and password for the Firebase console. Using my own clearly would not then have access to the Marvel AI Database.

The Google auth has not been merged in develop yet. You need to create your own firebase dB with firestore enabled, sign in & email auth enabled to use the given sign in crednetials. Ensure the env variables are set to your own firebase config

There are instructions on how to set up your local dev environment in the readme.

**Comment by patteesolomon** [comment]
> I am receiving this error regarding signing into the firebase project: extensions: Unable to look up project number for kai-platform-sandbox. [0] If this is a real project, ensure that you are logged in and have access to it. How do I get access to the marvel-ai kai-platform-sandbox?

setup your own port numbers. the login doesn't work tho.

**Comment by rettus-code** [comment]
Just joined today and got my environment up and running locally. I've used Firebase/Firestore and most of the other google services. I'd hate to create a lot of duplicate work. In the onboarding they did give us the option of collaborating if any of you are interested. With @liamohkay having an early start I'd suggest he take the lead and we could coordinate from their branch. Let me know what you think.

**Comment by Rockingfid1** [comment]
I'm currently stuck on implementing the user signup with google. I was able to implement the user sign-in with google functionality but implementing it with signing up has been tricky. Has anyone been able to come up with a  solution?

**Comment by liamohkay** [comment]
> I'm currently stuck on implementing the user signup with google. I was able to implement the user sign-in with google functionality but implementing it with signing up has been tricky. Has anyone been able to come up with a  solution?

Yes you can pull down my PR branch if you want to see a working solution

**Comment by Rockingfid1** [comment]
> > I'm currently stuck on implementing the user signup with google. I was able to implement the user sign-in with google functionality but implementing it with signing up has been tricky. Has anyone been able to come up with a  solution?
> 
> Yes you can pull down my PR branch if you want to see a working solution

whats your branch called

**Comment by Bhekisile** [comment]
Hi @liamohkay,I hope you won't mind if I check your code for sign-up with Google. Actually, I was so confused that I was under the impression that the sign-up was for signing up with an email and password. Thank you.
